player_name = input('Enter your full name:')
at_bats = int(input('Enter the number of at bats:'))
singles = int(input('Enter the number of singles:'))
doubles = int(input('Enter the number of doubles:'))
triples = int(input('Enter the number of triples:'))
hr = int(input('Enter the number of home runs:'))
hits = (singles + doubles + triples + hr)
bat_avg = (hits / at_bats)
bases_earned = (singles + (doubles * 2) + (triples * 3) + (hr * 4))
slug_perc = (bases_earned / at_bats)
print('The player', player_name, 'had', hits, "hits,")
print(singles, 'singles,', doubles, 'doubles,', triples, 'triples,', hr, 'homeruns,')
print('his batting average was', format(bat_avg, '.3f'))
print('his slugging percentage was', format(slug_perc, '.3f'))